### ISSUE TITLE
TODO: (maybe) restore camera correction code removed in 

### ISSUE THREAD

**Issue by tlambert03** [scopetools/cudadecon#32]
in #29, I commented out my camera correction code: https://github.com/scopetools/cudadecon/blob/21f7a80adc5ddc0c7e27e08be3823ff6c9c720de/src/llspy.cpp#L69-L91

(this is the code that backs [LLSpy Camera Corrections](https://llspy.readthedocs.io/en/latest/camera.html))

this is a TODO to remind me, and to welcome anyone who used it to comment

**Comment by jakirkham** [comment]
Given we now have working builds (thanks to your efforts! 😄), maybe a first step here is just submitting a PR that removes the comments to see what the error message is now?
