### ISSUE TITLE
update readme install instructions

### ISSUE THREAD

**Issue by tlambert03** [scopetools/cudadecon#40]
@jakirkham, i suspect i can update/simplify the current readme suggestions.  I think specifying cudatoolkit might be outdated?
and, do you agree i should just link to https://docs.nvidia.com/deploy/cuda-compatibility/ for the compatibility table?

-----

### GPU requirements

This software requires a CUDA-compatible NVIDIA GPU.
The libraries available on conda-forge have been compiled against different versions of the CUDA toolkit.  The required CUDA libraries are bundled in the conda distributions so you don't need to install the CUDA toolkit separately.  If desired, you can pick which version of CUDA you'd like based on your needs, but please note that different versions of the CUDA toolkit have different GPU driver requirements:

To specify a specific cudatoolkit version, install as follows (for instance, to use
`cudatoolkit=10.2`)

```sh
conda install -c conda-forge cudadecon cudatoolkit=10.2
```

| CUDA  | Linux driver | Win driver |
| ----- | ------------ | ---------- |
| 10.2  | ≥ 440.33     | ≥ 441.22   |
| 11.0  | ≥ 450.36.06  | ≥ 451.22   |
| 11.1  | ≥ 455.23     | ≥ 456.38   |
| 11.2  | ≥ 460.27.03  | ≥ 460.82   |

**Comment by jakirkham** [comment]
Yep great question Talley! 🙏

<hr>

Would suggest updating the command like so

```diff
-conda install -c conda-forge cudadecon cudatoolkit=10.2
+conda install -c conda-forge cudadecon cuda-version=<11 or 12>
```

On CUDA 11, there is `cudatoolkit`. On CUDA 12, the CUDA Toolkit has been disaggregated and previously missing pieces included.

The `cuda-version` package bridges over these differences. So should work the same from a user perspective

<hr>

At this point, we just build for CUDA 11.8 (for 11.x). For CUDA 12, we build on CUDA 12.0 and support CUDA 12.0+

The CUDA 11.8 build should work on the same hardware. There are some support changes in CUDA 12.0

In terms of the table, think we want to [reference this table]( https://docs.nvidia.com/deploy/cuda-compatibility/index.html#cuda-11-and-later-defaults-to-minor-version-compatibility )

<hr>

Please let me know if I missed anything or if you have more questions 🙂
