### ISSUE TITLE
Version numbering.

### ISSUE THREAD

**Issue by dmilkie** [scopetools/cudadecon#8]
Right now, the version number is hard coded [here](https://github.com/scopetools/cudaDecon/blob/8218b26fd345cd870acc008696dd7ce243996d9c/src/linearDecon.cpp#L13), and doesn't reflect the version in Github.

Should we implement some sort of Automatic generation of a header file containing version information? ala this:
https://github.com/smessmer/gitversion

**Comment by tlambert03** [comment]
yeah, that would be fantastic.  I've never gotten around to figuring out how to do it in C++.  If you can figure that out that would be awesome.  With that in place, and perhaps a basic document outline the steps required to bump the version, we can tag specific commits as releases and then turn on functionality to auto-upload tagged releases to anaconda in our CI builds.
